// Generated by android-icons/scripts/generate-icon-packs.mjs. Do not edit.
import CoreGraphics
import MapConductorIcons

/// Map symbols from the weather pack. Selection is always explicit.
public enum WeatherMapIcons {
    /// Clear daytime weather.
    public static let clearDay = MapIconGlyph(
        id: "weather.clear_day",
        commands: [
            .moveTo(CGPoint(x: 18, y: 12)),
            .curveTo(end: CGPoint(x: 12, y: 18), control1: CGPoint(x: 18, y: 15.3137), control2: CGPoint(x: 15.3137, y: 18)),
            .curveTo(end: CGPoint(x: 6, y: 12), control1: CGPoint(x: 8.6863, y: 18), control2: CGPoint(x: 6, y: 15.3137)),
            .curveTo(end: CGPoint(x: 12, y: 6), control1: CGPoint(x: 6, y: 8.6863), control2: CGPoint(x: 8.6863, y: 6)),
            .curveTo(end: CGPoint(x: 18, y: 12), control1: CGPoint(x: 15.3137, y: 6), control2: CGPoint(x: 18, y: 8.6863)),
            .close,
            .moveTo(CGPoint(x: 11, y: 1)),
            .lineTo(CGPoint(x: 13, y: 1)),
            .lineTo(CGPoint(x: 13, y: 5)),
            .lineTo(CGPoint(x: 11, y: 5)),
            .close,
            .moveTo(CGPoint(x: 11, y: 19)),
            .lineTo(CGPoint(x: 13, y: 19)),
            .lineTo(CGPoint(x: 13, y: 23)),
            .lineTo(CGPoint(x: 11, y: 23)),
            .close,
            .moveTo(CGPoint(x: 1, y: 11)),
            .lineTo(CGPoint(x: 5, y: 11)),
            .lineTo(CGPoint(x: 5, y: 13)),
            .lineTo(CGPoint(x: 1, y: 13)),
            .close,
            .moveTo(CGPoint(x: 19, y: 11)),
            .lineTo(CGPoint(x: 23, y: 11)),
            .lineTo(CGPoint(x: 23, y: 13)),
            .lineTo(CGPoint(x: 19, y: 13)),
            .close,
        ]
    )

    /// Cloudy weather.
    public static let cloud = MapIconGlyph(
        id: "weather.cloud",
        commands: [
            .moveTo(CGPoint(x: 5, y: 18)),
            .curveTo(end: CGPoint(x: 1, y: 14), control1: CGPoint(x: 2.8, y: 18), control2: CGPoint(x: 1, y: 16.2)),
            .curveTo(end: CGPoint(x: 4.7, y: 10), control1: CGPoint(x: 1, y: 11.9), control2: CGPoint(x: 2.6, y: 10.2)),
            .curveTo(end: CGPoint(x: 12, y: 5), control1: CGPoint(x: 5.5, y: 6.5), control2: CGPoint(x: 8.3, y: 5)),
            .curveTo(end: CGPoint(x: 19.2, y: 11.5), control1: CGPoint(x: 15.8, y: 5), control2: CGPoint(x: 18.8, y: 7.8)),
            .curveTo(end: CGPoint(x: 23, y: 16), control1: CGPoint(x: 21.4, y: 12), control2: CGPoint(x: 23, y: 13.8)),
            .curveTo(end: CGPoint(x: 19, y: 20), control1: CGPoint(x: 23, y: 18.2), control2: CGPoint(x: 21.2, y: 20)),
            .lineTo(CGPoint(x: 5, y: 20)),
            .close,
        ]
    )

    /// Rain.
    public static let rain = MapIconGlyph(
        id: "weather.rain",
        commands: [
            .moveTo(CGPoint(x: 5, y: 14)),
            .curveTo(end: CGPoint(x: 1, y: 10), control1: CGPoint(x: 2.8, y: 14), control2: CGPoint(x: 1, y: 12.2)),
            .curveTo(end: CGPoint(x: 4.7, y: 6), control1: CGPoint(x: 1, y: 7.9), control2: CGPoint(x: 2.6, y: 6.2)),
            .curveTo(end: CGPoint(x: 12, y: 1), control1: CGPoint(x: 5.5, y: 2.5), control2: CGPoint(x: 8.3, y: 1)),
            .curveTo(end: CGPoint(x: 19.2, y: 7.5), control1: CGPoint(x: 15.8, y: 1), control2: CGPoint(x: 18.8, y: 3.8)),
            .curveTo(end: CGPoint(x: 23, y: 12), control1: CGPoint(x: 21.4, y: 8), control2: CGPoint(x: 23, y: 9.8)),
            .curveTo(end: CGPoint(x: 19, y: 16), control1: CGPoint(x: 23, y: 14.2), control2: CGPoint(x: 21.2, y: 16)),
            .lineTo(CGPoint(x: 5, y: 16)),
            .close,
            .moveTo(CGPoint(x: 5, y: 18)),
            .lineTo(CGPoint(x: 8, y: 18)),
            .lineTo(CGPoint(x: 6, y: 23)),
            .lineTo(CGPoint(x: 3, y: 23)),
            .close,
            .moveTo(CGPoint(x: 11, y: 18)),
            .lineTo(CGPoint(x: 14, y: 18)),
            .lineTo(CGPoint(x: 12, y: 23)),
            .lineTo(CGPoint(x: 9, y: 23)),
            .close,
            .moveTo(CGPoint(x: 17, y: 18)),
            .lineTo(CGPoint(x: 20, y: 18)),
            .lineTo(CGPoint(x: 18, y: 23)),
            .lineTo(CGPoint(x: 15, y: 23)),
            .close,
        ]
    )

    /// Snow.
    public static let snow = MapIconGlyph(
        id: "weather.snow",
        commands: [
            .moveTo(CGPoint(x: 5, y: 14)),
            .curveTo(end: CGPoint(x: 1, y: 10), control1: CGPoint(x: 2.8, y: 14), control2: CGPoint(x: 1, y: 12.2)),
            .curveTo(end: CGPoint(x: 4.7, y: 6), control1: CGPoint(x: 1, y: 7.9), control2: CGPoint(x: 2.6, y: 6.2)),
            .curveTo(end: CGPoint(x: 12, y: 1), control1: CGPoint(x: 5.5, y: 2.5), control2: CGPoint(x: 8.3, y: 1)),
            .curveTo(end: CGPoint(x: 19.2, y: 7.5), control1: CGPoint(x: 15.8, y: 1), control2: CGPoint(x: 18.8, y: 3.8)),
            .curveTo(end: CGPoint(x: 23, y: 12), control1: CGPoint(x: 21.4, y: 8), control2: CGPoint(x: 23, y: 9.8)),
            .curveTo(end: CGPoint(x: 19, y: 16), control1: CGPoint(x: 23, y: 14.2), control2: CGPoint(x: 21.2, y: 16)),
            .lineTo(CGPoint(x: 5, y: 16)),
            .close,
            .moveTo(CGPoint(x: 5, y: 19)),
            .lineTo(CGPoint(x: 7, y: 17)),
            .lineTo(CGPoint(x: 9, y: 19)),
            .lineTo(CGPoint(x: 7, y: 21)),
            .close,
            .moveTo(CGPoint(x: 10, y: 22)),
            .lineTo(CGPoint(x: 12, y: 20)),
            .lineTo(CGPoint(x: 14, y: 22)),
            .lineTo(CGPoint(x: 12, y: 24)),
            .close,
            .moveTo(CGPoint(x: 15, y: 19)),
            .lineTo(CGPoint(x: 17, y: 17)),
            .lineTo(CGPoint(x: 19, y: 19)),
            .lineTo(CGPoint(x: 17, y: 21)),
            .close,
        ]
    )

    /// Thunderstorm.
    public static let thunderstorm = MapIconGlyph(
        id: "weather.thunderstorm",
        commands: [
            .moveTo(CGPoint(x: 5, y: 14)),
            .curveTo(end: CGPoint(x: 1, y: 10), control1: CGPoint(x: 2.8, y: 14), control2: CGPoint(x: 1, y: 12.2)),
            .curveTo(end: CGPoint(x: 4.7, y: 6), control1: CGPoint(x: 1, y: 7.9), control2: CGPoint(x: 2.6, y: 6.2)),
            .curveTo(end: CGPoint(x: 12, y: 1), control1: CGPoint(x: 5.5, y: 2.5), control2: CGPoint(x: 8.3, y: 1)),
            .curveTo(end: CGPoint(x: 19.2, y: 7.5), control1: CGPoint(x: 15.8, y: 1), control2: CGPoint(x: 18.8, y: 3.8)),
            .curveTo(end: CGPoint(x: 23, y: 12), control1: CGPoint(x: 21.4, y: 8), control2: CGPoint(x: 23, y: 9.8)),
            .curveTo(end: CGPoint(x: 19, y: 16), control1: CGPoint(x: 23, y: 14.2), control2: CGPoint(x: 21.2, y: 16)),
            .lineTo(CGPoint(x: 5, y: 16)),
            .close,
            .moveTo(CGPoint(x: 12, y: 15)),
            .lineTo(CGPoint(x: 18, y: 15)),
            .lineTo(CGPoint(x: 14, y: 19)),
            .lineTo(CGPoint(x: 17, y: 19)),
            .lineTo(CGPoint(x: 9, y: 24)),
            .lineTo(CGPoint(x: 11, y: 20)),
            .lineTo(CGPoint(x: 8, y: 20)),
            .close,
        ]
    )

    /// Wind.
    public static let wind = MapIconGlyph(
        id: "weather.wind",
        commands: [
            .moveTo(CGPoint(x: 2, y: 6)),
            .curveTo(end: CGPoint(x: 12, y: 3), control1: CGPoint(x: 7, y: 6), control2: CGPoint(x: 8, y: 3)),
            .curveTo(end: CGPoint(x: 17, y: 7), control1: CGPoint(x: 15, y: 3), control2: CGPoint(x: 17, y: 5)),
            .curveTo(end: CGPoint(x: 11, y: 11), control1: CGPoint(x: 17, y: 10), control2: CGPoint(x: 14, y: 11)),
            .lineTo(CGPoint(x: 2, y: 11)),
            .lineTo(CGPoint(x: 2, y: 8)),
            .lineTo(CGPoint(x: 11, y: 8)),
            .curveTo(end: CGPoint(x: 14, y: 7), control1: CGPoint(x: 13, y: 8), control2: CGPoint(x: 14, y: 8)),
            .curveTo(end: CGPoint(x: 12, y: 6), control1: CGPoint(x: 14, y: 6), control2: CGPoint(x: 13, y: 6)),
            .curveTo(end: CGPoint(x: 2, y: 9), control1: CGPoint(x: 9, y: 6), control2: CGPoint(x: 8, y: 9)),
            .close,
            .moveTo(CGPoint(x: 2, y: 14)),
            .lineTo(CGPoint(x: 17, y: 14)),
            .curveTo(end: CGPoint(x: 22, y: 18), control1: CGPoint(x: 20, y: 14), control2: CGPoint(x: 22, y: 16)),
            .curveTo(end: CGPoint(x: 16, y: 22), control1: CGPoint(x: 22, y: 21), control2: CGPoint(x: 19, y: 22)),
            .lineTo(CGPoint(x: 13, y: 22)),
            .lineTo(CGPoint(x: 13, y: 19)),
            .lineTo(CGPoint(x: 16, y: 19)),
            .curveTo(end: CGPoint(x: 19, y: 18), control1: CGPoint(x: 18, y: 19), control2: CGPoint(x: 19, y: 19)),
            .curveTo(end: CGPoint(x: 17, y: 17), control1: CGPoint(x: 19, y: 17), control2: CGPoint(x: 18, y: 17)),
            .lineTo(CGPoint(x: 2, y: 17)),
            .close,
        ]
    )

    /// Fog.
    public static let fog = MapIconGlyph(
        id: "weather.fog",
        commands: [
            .moveTo(CGPoint(x: 4, y: 5)),
            .lineTo(CGPoint(x: 20, y: 5)),
            .lineTo(CGPoint(x: 20, y: 8)),
            .lineTo(CGPoint(x: 4, y: 8)),
            .close,
            .moveTo(CGPoint(x: 1, y: 10)),
            .lineTo(CGPoint(x: 17, y: 10)),
            .lineTo(CGPoint(x: 17, y: 13)),
            .lineTo(CGPoint(x: 1, y: 13)),
            .close,
            .moveTo(CGPoint(x: 7, y: 15)),
            .lineTo(CGPoint(x: 23, y: 15)),
            .lineTo(CGPoint(x: 23, y: 18)),
            .lineTo(CGPoint(x: 7, y: 18)),
            .close,
            .moveTo(CGPoint(x: 3, y: 20)),
            .lineTo(CGPoint(x: 19, y: 20)),
            .lineTo(CGPoint(x: 19, y: 23)),
            .lineTo(CGPoint(x: 3, y: 23)),
            .close,
        ]
    )
}
